version: '3.4'

services:
  ubl-store:
    build:
      context: .
    environment:
      UBLSTORE_PORT: 80
      UBLSTORE_STORAGE_FILESYSTEM_UBLPATH: ./ubls
      UBLSTORE_STORAGE_FILESYSTEM_ATTACHMENTPATH: ./ attachments
      UBLSTORE_STORAGE_S3_UBLPATH: 
      UBLSTORE_STORAGE_S3_ATTACHMENTPATH: 
      UBLSTORE_STORAGE_S3_ENDPOINT: 
      UBLSTORE_STORAGE_S3_BUCKET: 
    volumes:
      - ./.data/ubl:/data/ubl-store/ubl
      - ./.data/attachment:/data/ubl-store/attachment
    ports:
      - 8080:80

 