version: '3.4'

services:
  ubl-store:
    build:
      context: .
    environment:
      UBLSTORE_PORT: 80
      UBLSTORE_STORAGE_FILESYSTEM_DATAPATH: 
      UBLSTORE_STORAGE_S3_ENDPOINT: http://minio:9000
      UBLSTORE_STORAGE_S3_BUCKET: ubl-store
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_REGION: us-east-1
    ports:
      - 8080:80

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./.minio/data:/export
      - ./.minio/config:/root/.minio
    command: server /export --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/ubl-store;
      /usr/bin/mc policy set download myminio/ubl-store;
      "