version: '3.4'

services:
  ubl-store:
    build:
      context: .
    environment:
      UBLSTORE_PORT: 80
      UBLSTORE_STORAGE_FILESYSTEM_DATAPATH: /data/ubl-store/
      UBLSTORE_STORAGE_S3_ENDPOINT: 
      UBLSTORE_STORAGE_S3_BUCKET: 
    volumes:
      - ./.data2:/data/ubl-store
    ports:
      - 8080:80

 