definitions:
  models.PostModel:
    properties:
      data:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/ubl:
    post:
      consumes:
      - application/json
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.PostModel'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Post ubl
      tags:
      - Ubl
  /api/v1/ubl/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Delete ubl
      tags:
      - Ubl
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Get ubl
      tags:
      - Ubl
swagger: "2.0"
